import "./globals.css";
import AuthGuard from "./authguard";

export const metadata = {
  title: "Junkshop Admin - ScrapCycle PH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/src/app/favicon.ico" />
      </head>
      <body className="bg-[#F8F8F8]">
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  );
}
